var GAME_LEVELS = [
  ["                                               xxx                              ",
   "                                    xxx       x!!!x                             ",
   "                                   x!!!x       x!x                              ",
   "                                    x!x         v                               ",
   "                                     v                                          ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                        ooo                                  x  ",
   "  x                          o     o   xxxxx                                 x  ",
   "  x           j             o     xxx              oo                      o x  ",
   "  x          xxx           o                      xxxx                       x  ",
   "  x  @       x x          o                                                  x  ",
   "  xxxxxxxxxxxx xxxxxxxxxxxxxxxx                            xxxxxxxxxxxxxxxxxxx  ",
   "                              x                            x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!x                    ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                    ",
   "                                                                                ",
   "                                                                                "],

  ["                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                              ",
   "                                                                                                          xxxx",
   "    b                                                                                                        x",
   "                                                                                                             x",
   "             b                                                                                         o   o x",
   "                                                                                                         xxxxx",
   " x                                                                o                                 oo        ",
   " x                                                                       oo                        xxxx       ",
   " x                                       o                             xxxxxx                                 ",
   " x     xxxxx                oo                              xxxxxx                            oo              ",
   " x    xx   x   x          xxxxxx       xxxx      x     x                           x     x   xxxx            x",
   " x @ xx    x   x!!!!!!!!!!x            x  x!!!!!!x  o  x!!!!!!!!!!!!!!!!!!!!!!!!!!!x  o  x!!!!!!!!!!!!!!!!!!!x",
   " xxxxx     x   x!!!!!!!!!!x            x  x!!!!!!x ooo x!!!!!!!!!!!!!!!!!!!!!!!!!!!x ooo x!!!!!!!!!!!!!!!!!!!x",
   "           x   xxxxxxxxxxxx   xxxxxxxxxx  x!!!!!!x ooo x!!!!!!!!!!!!!!!!!!!!!!!!!!!x ooo x!!!!!!!!!!!!!!!!!!!x",
   "           x                  x           x!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!x ooo x!!!!!!!!!!!!!!!!!!!x",
   "           x   oooooooooooo j x           x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xxxxx!!!!!!!!!!!!!!!!!!!!x",
   "           xxxxxxxxxxxxxxxxxxxx           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                                                                                                            ",
   "                 b                                                                                          ",
   "                                                                                                            ",
   "                                                           oo       oo                                      ",
   "                                                           xx       xx                                      ",
   "          b                                                                                                 ",
   "                                                      o                                                     ",
   "                                                     xxx                                                    ",
   "                                                                                                            ",
   "                  xxxxx                         o                                                           ",
   "               xxxx!!!!x                       xxx                                                          ",
   "            xxx!!!!!xvx                                                                                     ",
   "           x!!!!xvxx                                                                                        ",
   "            xvxx                        xxxx                                oooooooooooo                    ",
   "                                                                           xxxxxxxxxxxxxx                  x",
   "                                                                                             xxxxxx        x",
   "                         o          xxxx                                                                   x",
   "                      xxxxx                                                                          x!   !x",
   "                    o x   x!                                                                         x! o !x",
   "  x               xxxxx   x! o  xxx                                                                  x! o !x",
   "  x             o x       x! o !x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x! o !x",
   "  x           xxxxx       x! o !x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x! o !x",
   "  x      @    x           x! o !x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x! o !x",
   "  xxxxxxxxxxxxx           x! j !x x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x! o !x",
   "                          xxxxxxx x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x! o !x",
   "                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"],

  ["                                                                                                         ",
   "                                                                                                         ",
   "   x                                                                                                  x  ",
   "   x                                                                                                  x  ",
   "   x                                                                                                  x  ",
   "   x                                                                                                  x  ",
   "   x                                                                                                  x  ",
   "   x      o       o     oooooooo     o        o             o            o   ooooooooo   o     o      x  ",
   "   x       o     o     o        o    o        o             o     o      o       o       oo    o      x  ",
   "   x        o   o      o        o    o        o             o     o      o       o       o o   o      x  ",
   "   x          o        o        o    o        o             o     o      o       o       o  o  o      x  ",
   "   x          o        o        o    o        o             o     o      o       o       o   o o      x  ",
   "   x          o        o        o    o        o              o   o  o   o        o       o    oo      x  ",
   "   x  @  j    o         oooooooo      oooooooo                 o      o      ooooooooo   o     o      x  ",
   "   xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                         "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
